title: vuurcode.dev
subtitle: Forty by HTML5 UP
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: ""
url: "https://vuurcode.dev"
author:
  name: Vuurcode
  email: info@vuurcode.dev
  phone: ""
  address: ""

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
socials:
  - title: GitHub
    icon: fa-github
    url: https://github.com/vuurcode

# build settings
markdown: kramdown
sass:
  style: compressed
