title: vuurcode.dev
subtitle: Forty by HTML5 UP
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: ""
url: "https://vuurcode.dev"
author:
  name: Vuurcode

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 2

# social settings
socials:
  GitHub: https://github.com/vuurcode

# build settings
markdown: kramdown
sass:
  style: compressed
